[package]
name = "dunce"
version = "0.1.0"
authors = ["Dave Bonner <dbonner@gmail.com>"]
edition = "2018"
license = "GPL-3.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
rand = "0.7.2"
